### ISSUE TITLE
Error 12002 has occurred

### ISSUE THREAD

**Issue by kr1staa** [Ochii/cso2-master-server#33] opened 2019-02-03 04:08 UTC
![p8ldsl 65 w 7uv25a n b](https://user-images.githubusercontent.com/47288667/52172536-40691f00-27ac-11e9-8149-3f43f90afc54.png)
 i cant start the game, how to set the server sv_cheat 1?

**Comment by GEEKiDoS** [comment] 2019-02-03 17:01
https://github.com/Ochii/cso2-launcher/issues/20#issue-405969049

Maybe a similar issue

**Comment by Ochii** [comment] 2019-02-03 17:14
Duplicate of Ochii/cso2-launcher#20

**Closed by Ochii** 2019-02-03 17:14 UTC
Labels: bug, question
