### ISSUE TITLE
game start error

### ISSUE THREAD

**Issue by DebugBios** [Ochii/cso2-master-server#5] opened 2018-10-21 22:41 UTC
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@6.4.1
3 info using node@v8.12.0
4 verbose config Skipping project config: C:\Users\admin/.npmrc. (matches userconfig)
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info lifecycle cso2-master-server@0.1.0~prestart: cso2-master-server@0.1.0
7 info lifecycle cso2-master-server@0.1.0~start: cso2-master-server@0.1.0
8 verbose lifecycle cso2-master-server@0.1.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle cso2-master-server@0.1.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\admin\node_modules\.bin;C:\Users\admin\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;c:\devkitPro\msys\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;C:\Users\admin\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Bandizip\;C:\Users\admin\AppData\Roaming\npm
10 verbose lifecycle cso2-master-server@0.1.0~start: CWD: C:\Users\admin
11 silly lifecycle cso2-master-server@0.1.0~start: Args: [ '/d /s /c', 'node dist/server.js' ]
12 silly lifecycle cso2-master-server@0.1.0~start: Returned: code: 1  signal: null
13 info lifecycle cso2-master-server@0.1.0~start: Failed to exec start script
14 verbose stack Error: cso2-master-server@0.1.0 start: `node dist/server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:915:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid cso2-master-server@0.1.0
16 verbose cwd C:\Users\admin
17 verbose Windows_NT 10.0.17134
18 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
19 verbose node v8.12.0
20 verbose npm  v6.4.1
21 error code ELIFECYCLE
22 error errno 1
23 error cso2-master-server@0.1.0 start: `node dist/server.js`
23 error Exit status 1
24 error Failed at the cso2-master-server@0.1.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by Ochii** [comment] 2018-10-22 17:48
I don't understand what the issue is

**Comment by DebugBios** [comment] 2018-10-22 18:34
> 문제가 무엇인지 이해하지 못합니다.

![default](https://user-images.githubusercontent.com/44349391/47311278-3d6e7680-d674-11e8-979c-c96cc058e97b.PNG)

If you click on "게임 시작", it goes off by saying, "서버와의 연결이 끊겼습니다." (The connection to the server has been lost)

**Comment by Ochii** [comment] 2018-11-13 12:57
Please try the [new release](https://github.com/Ochii/cso2-master-server/releases/tag/v0.2.0)

**Comment by DebugBios** [comment] 2018-11-13 15:12
C:\Users\rat96>npm run start

> cso2-master-server@0.2.0 start C:\Users\rat96
> node dist/server.js

No IP address given!
Usage: server [options]

Options:
  -V, --version                output the version number
  -i, --ip-address <ip>        The IP address to be used by the server
  -p, --port-master [port]     The server's (TCP) port (default: 30001)
  -P, --port-holepunch [port]  The server's holepunch (UDP) port (default: 30002)
  -h, --help                   output usage information

Usage: server [options]

Options:
  -V, --version                output the version number
  -i, --ip-address <ip>        The IP address to be used by the server
  -p, --port-master [port]     The server's (TCP) port (default: 30001)
  -P, --port-holepunch [port]  The server's holepunch (UDP) port (default: 30002)
  -h, --help                   output usage information
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cso2-master-server@0.2.0 start: `node dist/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cso2-master-server@0.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rat96\AppData\Roaming\npm-cache\_logs\2018-11-13T15_10_21_554Z-debug.log

**Comment by DebugBios** [comment] 2018-11-13 15:12
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@5.6.0
3 info using node@v8.11.4
4 verbose config Skipping project config: C:\Users\rat96/.npmrc. (matches userconfig)
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info lifecycle cso2-master-server@0.2.0~prestart: cso2-master-server@0.2.0
7 info lifecycle cso2-master-server@0.2.0~start: cso2-master-server@0.2.0
8 verbose lifecycle cso2-master-server@0.2.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle cso2-master-server@0.2.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\rat96\node_modules\.bin;C:\Users\rat96\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\OpenVPN\bin;C:\Program Files\nodejs\;C:\Users\rat96\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Bandizip\;C:\Users\rat96\AppData\Roaming\npm
10 verbose lifecycle cso2-master-server@0.2.0~start: CWD: C:\Users\rat96
11 silly lifecycle cso2-master-server@0.2.0~start: Args: [ '/d /s /c', 'node dist/server.js' ]
12 silly lifecycle cso2-master-server@0.2.0~start: Returned: code: 1  signal: null
13 info lifecycle cso2-master-server@0.2.0~start: Failed to exec start script
14 verbose stack Error: cso2-master-server@0.2.0 start: `node dist/server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid cso2-master-server@0.2.0
16 verbose cwd C:\Users\rat96
17 verbose Windows_NT 10.0.17134
18 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
19 verbose node v8.11.4
20 verbose npm  v5.6.0
21 error code ELIFECYCLE
22 error errno 1
23 error cso2-master-server@0.2.0 start: `node dist/server.js`
23 error Exit status 1
24 error Failed at the cso2-master-server@0.2.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by Ochii** [comment] 2018-11-13 15:14
try running with ```npm run start -- --ip-address [your network IP address]```

**Comment by DebugBios** [comment] 2018-11-13 15:14
Error occurs when executing.

**Comment by DebugBios** [comment] 2018-11-13 15:16
C:\Users\rat96>npm run start -- --ip-address [119.201.14.144]

> cso2-master-server@0.2.0 start C:\Users\rat96
> node dist/server.js "--ip-address" "[119.201.14.144]"

Using command line arguments --ip-address as [119.201.14.144]
--port-master as 30001
--port-holepunch as 30002
server error: getaddrinfo ENOTFOUND [119.201.14.144]
C:\Users\rat96\dist\serverinstance.js:112
        throw err;
        ^

Error: getaddrinfo ENOTFOUND [119.201.14.144]
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cso2-master-server@0.2.0 start: `node dist/server.js "--ip-address" "[119.201.14.144]"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cso2-master-server@0.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rat96\AppData\Roaming\npm-cache\_logs\2018-11-13T15_15_11_881Z-debug.log

**Comment by DebugBios** [comment] 2018-11-13 15:16
info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start',
1 verbose cli   '--',
1 verbose cli   '--ip-address',
1 verbose cli   '[119.201.14.144]' ]
2 info using npm@5.6.0
3 info using node@v8.11.4
4 verbose config Skipping project config: C:\Users\rat96/.npmrc. (matches userconfig)
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info lifecycle cso2-master-server@0.2.0~prestart: cso2-master-server@0.2.0
7 info lifecycle cso2-master-server@0.2.0~start: cso2-master-server@0.2.0
8 verbose lifecycle cso2-master-server@0.2.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle cso2-master-server@0.2.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\rat96\node_modules\.bin;C:\Users\rat96\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\OpenVPN\bin;C:\Program Files\nodejs\;C:\Users\rat96\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Bandizip\;C:\Users\rat96\AppData\Roaming\npm
10 verbose lifecycle cso2-master-server@0.2.0~start: CWD: C:\Users\rat96
11 silly lifecycle cso2-master-server@0.2.0~start: Args: [ '/d /s /c',
11 silly lifecycle   'node dist/server.js "--ip-address" "[119.201.14.144]"' ]
12 silly lifecycle cso2-master-server@0.2.0~start: Returned: code: 1  signal: null
13 info lifecycle cso2-master-server@0.2.0~start: Failed to exec start script
14 verbose stack Error: cso2-master-server@0.2.0 start: `node dist/server.js "--ip-address" "[119.201.14.144]"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid cso2-master-server@0.2.0
16 verbose cwd C:\Users\rat96
17 verbose Windows_NT 10.0.17134
18 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start" "--" "--ip-address" "[119.201.14.144]"
19 verbose node v8.11.4
20 verbose npm  v5.6.0
21 error code ELIFECYCLE
22 error errno 1
23 error cso2-master-server@0.2.0 start: `node dist/server.js "--ip-address" "[119.201.14.144]"`
23 error Exit status 1
24 error Failed at the cso2-master-server@0.2.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by Ochii** [comment] 2018-11-13 15:20
Try using your machine internal network IP (for example, 192.168.1.100)

There is no need to send the entire log, everything before ```npm ERR! code ELIFECYCLE``` is enough.

And for your safety, don't put your external IP address here next time

**Comment by lemnrt** [comment] 2018-11-13 15:29
try
npm run start - --ip-address 192.168.1.100

**Comment by DebugBios** [comment] 2018-11-13 15:30
No IP address given!
Usage: server [options]

Options:
  -V, --version                output the version number
  -i, --ip-address <ip>        The IP address to be used by the server
  -p, --port-master [port]     The server's (TCP) port (default: 30001)
  -P, --port-holepunch [port]  The server's holepunch (UDP) port (default: 30002)
  -h, --help                   output usage information

Usage: server [options]

Options:
  -V, --version                output the version number
  -i, --ip-address <ip>        The IP address to be used by the server
  -p, --port-master [port]     The server's (TCP) port (default: 30001)
  -P, --port-holepunch [port]  The server's holepunch (UDP) port (default: 30002)
  -h, --help

**Comment by lemnrt** [comment] 2018-11-13 15:34
npm run start -- --ip-address 127.0.0.1

**Comment by DebugBios** [comment] 2018-11-13 15:42
Error occurs when a room is created.

**Comment by DebugBios** [comment] 2018-11-13 15:45
![cso2_0001](https://user-images.githubusercontent.com/44349391/48424712-8793d500-e7a6-11e8-8a50-005fd1ca0514.jpg)

**Comment by DebugBios** [comment] 2018-11-13 18:45
![default](https://user-images.githubusercontent.com/44349391/48435099-f2510a80-e7be-11e8-94b0-51d1afff6cb5.PNG)
If I did not use 127.0.0.1 and I use the correct LAN IP 게임 서버에 접속하지 못했습니다. (Failed to connect to the game server.) The error says

**Comment by Ochii** [comment] 2018-11-13 18:46
The client seems to be broken, I'm working on a fix

**Comment by DebugBios** [comment] 2018-11-18 22:08
Crash occurs when you create a room in the Korean version.

Error: Data buffer is too small
    at InRoomPacket.readUInt32 (C:\Users\admin\dist\packets\in\packet.js:112:19)
    at new InRoomNewRequest (C:\Users\admin\dist\packets\in\room\fullrequest.js:25:31)
    at InRoomPacket.parse (C:\Users\admin\dist\packets\in\room.js:74:35)
    at new InPacketBase (C:\Users\admin\dist\packets\in\packet.js:21:14)
    at new InRoomPacket (C:\Users\admin\dist\packets\in\room.js:23:1)
    at ChannelManager.onRoomRequest (C:\Users\admin\dist\channel\channelmanager.js:74:27)
    at ServerInstance.onIncomingPacket (C:\Users\admin\dist\serverinstance.js:186:38)
    at ServerInstance.onSocketData (C:\Users\admin\dist\serverinstance.js:160:14)
    at Socket.newSocket.on (C:\Users\admin\dist\serverinstance.js:85:18)
    at emitOne (events.js:116:13)

**Comment by DebugBios** [comment] 2018-12-09 08:21
Unable to change the team, the person entering the room cannot see the bot, and when the game starts, each person gets up with a crash.


Error: This is not a packet
    at InPacketBase.parse (C:\Users\admin\dist\packets\in\packet.js:181:19)
    at new InPacketBase (C:\Users\admin\dist\packets\in\packet.js:21:14)
    at ServerInstance.onIncomingPacket (C:\Users\admin\dist\serverinstance.js:169:24)
    at ServerInstance.onSocketData (C:\Users\admin\dist\serverinstance.js:160:14)
    at Socket.newSocket.on (C:\Users\admin\dist\serverinstance.js:85:18)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)
    at Socket.Readable.push (_stream_readable.js:208:10)

**Comment by DebugBios** [comment] 2018-12-09 15:05
Also, when a game is played with a LAN IP address, the server crashes when a room is created, and when a game is played with 127.0.0.1 the player crashes.


https://youtu.be/w8mhG11y41w

**Comment by Ochii** [comment] 2018-12-09 15:10
> 
> 
> Also, when a game is played with a LAN IP address, the server crashes when a room is created, and when a game is played with 127.0.0.1 the player crashes.
> 
> https://youtu.be/w8mhG11y41w

That seems to be related to issue #6.

I have opened issue #9 for the team changing crash.

With that I'll close this issue.

**Closed by Ochii** 2018-12-09 15:10 UTC
Labels: needsinfo
